export {default as MainMovie} from './MainMovie.vue'
export {default as MainTv} from './MainTv.vue'
export {default as MovieCard} from './MovieCard.vue'
export {default as Nav} from './Nav.vue'
export {default as Search} from './Search.vue'
export {default as Poster} from './Poster.vue'